"""GrainWorld R50, G448+L192. Fresh training from an image-backbone pretrain.

There is one public model configuration. Internal class and parameter names
are retained so existing G448+L192 checkpoints load without conversion.
"""

model = {'type': 'Q4OccPhase1PerformanceBatchSafeSparseWorld',
 'use_grid_mask': False,
 'data_aug': {'img_color_aug': True,
              'img_norm_cfg': {'mean': [123.675, 116.28, 103.53],
                               'std': [58.395, 57.12, 57.375],
                               'to_rgb': True},
              'img_pad_cfg': {'size_divisor': 32}},
 'stop_prev_grad': 0,
 'img_backbone': {'type': 'ResNet',
                  'depth': 50,
                  'num_stages': 4,
                  'out_indices': (0, 1, 2, 3),
                  'frozen_stages': 1,
                  'norm_cfg': {'type': 'BN2d', 'requires_grad': True},
                  'norm_eval': True,
                  'style': 'pytorch',
                  'with_cp': True},
 'img_neck': {'type': 'FPN',
              'in_channels': [256, 512, 1024, 2048],
              'out_channels': 256,
              'num_outs': 4},
 'pts_bbox_head': {'type': 'Q4OccPhase1PerformanceBatchSafeHead',
                   'num_classes': 17,
                   'in_channels': 256,
                   'num_query': 600,
                   'future_frames': [0, 2, 4, 6],
                   'pc_range': [-40.0, -40.0, -1.0, 40.0, 40.0, 5.4],
                   'voxel_size': [0.4, 0.4, 0.4],
                   'transformer': {'type': 'DualContextJointTransformer',
                                   'embed_dims': 256,
                                   'num_frames': 8,
                                   'future_frames': [0, 2, 4, 6],
                                   'num_points': 4,
                                   'num_layers': 6,
                                   'num_levels': 4,
                                   'num_classes': 17,
                                   'num_refines': [1, 4, 16, 32, 64, 128],
                                   'scales': [0.5],
                                   'pc_range': [-40.0, -40.0, -1.0, 40.0, 40.0, 5.4],
                                   'q4occ': {'enabled': True,
                                             'phase': 'phase1_performance',
                                             'num_latents': 448,
                                             'temporal_layers': 2,
                                             'latent_layers': 1,
                                             'decoder_layers': 6,
                                             'num_heads': 8,
                                             'ffn_ratio': 4.0,
                                             'dropout': 0.0,
                                             'query_self_attention': False,
                                             'decode_fraction': 1.0,
                                             'sensor_anchor_extent': [0.00625,
                                                                      0.00625,
                                                                      0.015625],
                                             'valid_feature_epsilon': 1e-08,
                                             'memory_geometry_grad_scale': 0.0,
                                             'dual_memory': True,
                                             'local_memory_tokens': 192,
                                             'joint_query_interaction': True,
                                             'joint_memory_layer_scale_init': 0.001,
                                             'detach_memory_prepass': True,
                                             'joint_local_memory_scope': 'all',
                                             'parallel_memory_fusion': True,
                                             'joint_global_memory_enabled': True,
                                             'joint_local_memory_enabled': True,
                                             'align_frame_group_sampling': False}},
                   'loss_cls': {'type': 'FocalLoss',
                                'use_sigmoid': True,
                                'gamma': 2.0,
                                'alpha': 0.25,
                                'loss_weight': 2.0},
                   'loss_pts': {'type': 'SmoothL1Loss', 'beta': 0.2, 'loss_weight': 0.5},
                   'use_can_bus': False},
 'train_cfg': {'pts': {'cls_weights': [10,
                                       5,
                                       10,
                                       5,
                                       5,
                                       10,
                                       10,
                                       5,
                                       10,
                                       5,
                                       5,
                                       1,
                                       5,
                                       1,
                                       1,
                                       2,
                                       1]}},
 'test_cfg': {'pts': {'score_thr': 0.5, 'padding': True}}}

data = {'workers_per_gpu': 4,
 'train': {'type': 'NuScenesOccDataset',
           'future_frames': [0, 2, 4, 6],
           'data_root': 'data/nuscenes/',
           'ann_file': 'data/nuscenes/nuscenes_infos_train_sweep_occ.pkl',
           'pipeline': [{'type': 'LoadMultiViewImageFromFiles',
                         'to_float32': False,
                         'color_type': 'color'},
                        {'type': 'LoadMultiViewImageFromMultiSweeps', 'sweeps_num': 7},
                        {'type': 'LoadAnnotations3D',
                         'with_bbox_3d': True,
                         'with_label_3d': True,
                         'with_attr_label': False},
                        {'type': 'LoadOccFromFile',
                         'occ_root': 'data/nuscenes/gts/',
                         'future_frames': [0, 2, 4, 6]},
                        {'type': 'ObjectRangeFilter',
                         'point_cloud_range': [-40.0, -40.0, -1.0, 40.0, 40.0, 5.4]},
                        {'type': 'ObjectNameFilter',
                         'classes': ['car',
                                     'truck',
                                     'construction_vehicle',
                                     'bus',
                                     'trailer',
                                     'barrier',
                                     'motorcycle',
                                     'bicycle',
                                     'pedestrian',
                                     'traffic_cone']},
                        {'type': 'RandomTransformImage',
                         'ida_aug_conf': {'resize_lim': (0.38, 0.55),
                                          'final_dim': (256, 704),
                                          'bot_pct_lim': (0.0, 0.0),
                                          'rot_lim': (0.0, 0.0),
                                          'H': 900,
                                          'W': 1600,
                                          'rand_flip': True},
                         'training': True},
                        {'type': 'DefaultFormatBundle3D',
                         'class_names': ['car',
                                         'truck',
                                         'construction_vehicle',
                                         'bus',
                                         'trailer',
                                         'barrier',
                                         'motorcycle',
                                         'bicycle',
                                         'pedestrian',
                                         'traffic_cone']},
                        {'type': 'Collect3D',
                         'keys': ['img',
                                  'voxel_semantics',
                                  'mask_camera',
                                  'future_valid',
                                  'fut2cur',
                                  'fut_list'],
                         'meta_keys': ('filename',
                                       'ori_shape',
                                       'img_shape',
                                       'pad_shape',
                                       'lidar2img',
                                       'img_timestamp',
                                       'ego2lidar',
                                       'lidar2cam',
                                       'intrinsics',
                                       'extrinsics')}],
           'classes': ['car',
                       'truck',
                       'construction_vehicle',
                       'bus',
                       'trailer',
                       'barrier',
                       'motorcycle',
                       'bicycle',
                       'pedestrian',
                       'traffic_cone'],
           'modality': {'use_lidar': False,
                        'use_camera': True,
                        'use_radar': False,
                        'use_map': False,
                        'use_external': True},
           'test_mode': False,
           'use_valid_flag': True,
           'box_type_3d': 'LiDAR'},
 'val': {'type': 'NuScenesOccDataset',
         'future_frames': [0, 2, 4, 6],
         'data_root': 'data/nuscenes/',
         'ann_file': 'data/nuscenes/nuscenes_infos_val_sweep_occ.pkl',
         'pipeline': [{'type': 'LoadMultiViewImageFromFiles',
                       'to_float32': False,
                       'color_type': 'color'},
                      {'type': 'LoadMultiViewImageFromMultiSweeps',
                       'sweeps_num': 7,
                       'test_mode': True},
                      {'type': 'RandomTransformImage',
                       'ida_aug_conf': {'resize_lim': (0.38, 0.55),
                                        'final_dim': (256, 704),
                                        'bot_pct_lim': (0.0, 0.0),
                                        'rot_lim': (0.0, 0.0),
                                        'H': 900,
                                        'W': 1600,
                                        'rand_flip': True},
                       'training': False},
                      {'type': 'LoadOccFromFile',
                       'occ_root': 'data/nuscenes/gts/',
                       'future_frames': [0, 2, 4, 6],
                       'pred_traj': False},
                      {'type': 'MultiScaleFlipAug3D',
                       'img_scale': (1600, 900),
                       'pts_scale_ratio': 1,
                       'flip': False,
                       'transforms': [{'type': 'DefaultFormatBundle3D',
                                       'class_names': ['car',
                                                       'truck',
                                                       'construction_vehicle',
                                                       'bus',
                                                       'trailer',
                                                       'barrier',
                                                       'motorcycle',
                                                       'bicycle',
                                                       'pedestrian',
                                                       'traffic_cone'],
                                       'with_label': False},
                                      {'type': 'Collect3D',
                                       'keys': ['img', 'fut2cur', 'fut_list'],
                                       'meta_keys': ('filename',
                                                     'box_type_3d',
                                                     'ori_shape',
                                                     'img_shape',
                                                     'pad_shape',
                                                     'lidar2img',
                                                     'img_timestamp',
                                                     'ego2lidar',
                                                     'lidar2cam',
                                                     'intrinsics',
                                                     'extrinsics')}]}],
         'classes': ['car',
                     'truck',
                     'construction_vehicle',
                     'bus',
                     'trailer',
                     'barrier',
                     'motorcycle',
                     'bicycle',
                     'pedestrian',
                     'traffic_cone'],
         'modality': {'use_lidar': False,
                      'use_camera': True,
                      'use_radar': False,
                      'use_map': False,
                      'use_external': True},
         'test_mode': True,
         'box_type_3d': 'LiDAR'}}

future_frames = [0, 2, 4, 6]

point_cloud_range = [-40.0, -40.0, -1.0, 40.0, 40.0, 5.4]

voxel_size = [0.4, 0.4, 0.4]

dataset_root = 'data/nuscenes/'

occ_root = 'data/nuscenes/gts/'

optimizer = {'type': 'AdamW',
 'lr': 0.0003,
 'paramwise_cfg': {'custom_keys': {'img_backbone': {'lr_mult': 0.1},
                                   'sampling_offset': {'lr_mult': 0.1}}},
 'weight_decay': 0.01}

optimizer_config = {'type': 'GradientCumulativeFp16OptimizerHook',
 'loss_scale': 512.0,
 'grad_clip': {'max_norm': 35, 'norm_type': 2},
 'cumulative_iters': 1}

lr_config = {'policy': 'CosineAnnealing',
 'warmup': 'linear',
 'warmup_iters': 500,
 'warmup_ratio': 0.3333333333333333,
 'min_lr_ratio': 0.001}

total_epochs = 80

batch_size = 8

find_unused_parameters = False

checkpoint_config = {'interval': 5, 'save_last': True, 'max_keep_ckpts': -1}

log_config = {'interval': 50, 'hooks': [{'type': 'TextLoggerHook'}]}

validation_interval = 5
seed = 0
